### ISSUE TITLE
In homepage, Manage Alignment of features in body part.

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#1]
I was checking homepage which always comes first after login and while scrolling down i saw youtube boxes,Traffic Sign,Traffic rules and Metro FM was not aligned properly as it in design. 
![image](https://user-images.githubusercontent.com/128671409/228767440-d17a0234-ef6b-45c0-a4b2-2d316bebd1ed.png)

**Comment by sachinjnk99** [comment]
![image](https://user-images.githubusercontent.com/128477532/228877185-62136101-2340-4bab-8574-f32a55665df4.png)
Hello BA 
I have made changes in dashboard.....

**Comment by tseringklama** [comment]
Issue solved .
