### ISSUE TITLE
Add traffic on Traffic features of Admin panel issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#10]
While i was testing system i found out that Add traffic of Traffic features on Admin panel shows Signup of user instead of Signup of Traffic so i would like you to solve this issue righnow. Thankyou 
<img width="1280" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/25e7a227-03cc-41cc-8a27-5a901b6f9a86">
<img width="1277" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/99d01f1a-ee61-482d-bf85-4697172201d2">

**Comment by saringrg** [comment]
![add traffic](https://github.com/saringrg/TMS/assets/128318185/719661f3-f588-47aa-a80b-58ef764b0b67)
The issue has been tracked and the code has been updated. The button now, redirects to the traffic signup.
