### ISSUE TITLE
E-chit pdf issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#11]
While i was testing E-chit features and sending mail to me there i found that E-chit number has 4 digit integers, According to government Chit there should be 6 digit. E-chit alignment should be on right side where there i found on the left. 
<img width="781" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/bf8f859d-3c8c-433c-a469-2fb5b95748b2">

**Comment by saringrg** [comment]
![otp](https://github.com/saringrg/TMS/assets/128318185/e761ff07-88e5-42db-956f-f14bc2ee9bc2)
![alignment](https://github.com/saringrg/TMS/assets/128318185/bfe5d607-419b-41da-ae70-d363749a083d)
The file has been updated, six digit chit number is generated automatically, and the alignment too has been changed to right as required

**Comment by saringrg** [comment]
![image](https://github.com/saringrg/TMS/assets/128318185/97b089a7-f92f-481a-a474-9ce654e3658e)
