### ISSUE TITLE
Video alignment issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#12]
While i was checking User home page video of Traffic was not in correct alignment as it is in design so i would like to request sachin to correct and make it in right way in the centre alignment Thank you.
![image](https://github.com/saringrg/TMS/assets/128671409/9c5f62ad-252f-4275-a173-0f52198c965f)

**Comment by sachinjnk99** [comment]
![image](https://github.com/saringrg/TMS/assets/128477532/73c4e9e4-f1f7-4965-8fc6-28907649f27f)
Hello tsering, I had made the design same as wireframe now. so, please review and match the design with wireframe and also give me some feedback

**Comment by tseringklama** [comment]
thank you sachin.
