### ISSUE TITLE
Complain Box design issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#13]
While i was checking Complain box features of User and testing there was found incorrect design of Complain box which was not same as my design. box was too larger compare to mine so i would like to request Sachin to correct in right way as my design. Thankyou. 
![image](https://github.com/saringrg/TMS/assets/128671409/f7d3a591-5d8e-4fa8-b222-94f1e43cc34a)

**Comment by sachinjnk99** [comment]
![image](https://github.com/saringrg/TMS/assets/128477532/d3ea30d3-55f8-4881-b153-94ccb8fae58e)
 Hello Tsering, I had made changes in the design 
please, review the design and give me some feedback
