### ISSUE TITLE
Echit edit in admin panel issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#14]
While i was testing echit edit on echit details of admin panel when i was trying to reload to check what will happen. There was found error on echit edit panel.
<img width="965" alt="Screen Shot 2023-05-14 at 12 38 32" src="https://github.com/saringrg/TMS/assets/128671409/bfd11413-6cca-4cbe-a7c6-25940a2f2547">

**Comment by Yajan28** [comment]
<img width="482" alt="image" src="https://github.com/saringrg/TMS/assets/127926933/8dfe27e6-344e-4446-bcc7-37a448126c65">

**Comment by tseringklama** [comment]
Thank you Yajan for solving
