### ISSUE TITLE
Traffic delete issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#15]
While i was testing Traffic details of admin panel and tried to delete there was found // Delete // instead of Delete  itself. so i would like to assign Yajan to solve this issue. 
<img width="1280" alt="Screen Shot 2023-05-14 at 12 50 59" src="https://github.com/saringrg/TMS/assets/128671409/ce836be4-cf5d-469e-8072-9d15759c4f15">

**Comment by Yajan28** [comment]
<img width="482" alt="image" src="https://github.com/saringrg/TMS/assets/127926933/4f7e1a34-fe32-40e4-846f-88333bd801be">

**Comment by tseringklama** [comment]
Thank you Yajan for solving.
