### ISSUE TITLE
echit details of Admin panel issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#17]
While i was testing echit details of Admin panel there was written Chit No. instead of Chit Number . It was written in short form might be done in during hurry. I would like  Manshi to do in correct way with formal . 
<img width="1280" alt="Screen Shot 2023-05-14 at 13 06 30" src="https://github.com/saringrg/TMS/assets/128671409/f920198d-ccd6-4bb9-ac03-00dae75262fe">

**Comment by manshigrg** [comment]
![image](https://github.com/saringrg/TMS/assets/128445802/99db0bed-5812-44fa-a83b-de54ac74fea1)
the isssue has been solved

**Comment by tseringklama** [comment]
Thank you manshi.
