### ISSUE TITLE
Unable to display data of complain in admin panel

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#19]
When i was testing Complain of admin panel while pressing complain.  I am unable to redirect to complain.php page.
<img width="332" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/6ec9474f-41ac-4966-9eee-489c3d9743b7">

**Comment by saringrg** [comment]
![image](https://github.com/saringrg/TMS/assets/128318185/4ac808dc-e15a-480e-ab8b-df0ae804ca74)
the file has been updated to correctly direct to the cmplain.php
