### ISSUE TITLE
Database of E-Chit Vehicle number datatype issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#2]
I was checking database and found out that Vehicle number is in integers but it should be on Varchar both the character and integers.

<img width="1009" alt="vehicle number issue" src="https://user-images.githubusercontent.com/128671409/228776702-79c2e543-44b9-4173-8b50-7560231bad53.png">

**Comment by saringrg** [comment]
![db](https://user-images.githubusercontent.com/128318185/229111025-106244e5-456e-4ed8-b577-def0373a2ddd.jpg)
@tseringklama the data type has been changed from int to varchar
![inttovar](https://user-images.githubusercontent.com/128318185/229111037-0d226ba9-345e-4e85-b9d6-21c0a852e2c3.jpg)
and the code too has been updated for the above issue

**Comment by tseringklama** [comment]
Yes issue is completed. Now it is done.
