### ISSUE TITLE
Unable to login to user panel after logging out from the admin panel

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#20]
When i was testing log out from admin panel and trying to switch into user panel , I am unable to login to user panel.<img width="332" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/4fd7846b-6e43-47d9-b1ff-d0223df8f9d4">

**Comment by saringrg** [comment]
![image](https://github.com/saringrg/TMS/assets/128318185/1812e206-e2f7-4b4d-99b3-00eace468201)
the link has been updated to solve the login issue

**Comment by tseringklama** [comment]
Thank you Sarin.
