### ISSUE TITLE
Complain box of User panel issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#22]
While i was testing complain box of user panel i submitted without entering details and it went successfully which is bug.
<img width="1171" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/cb97fb3b-ce84-45dc-9198-fe901a120a04">

**Comment by sachinjnk99** [comment]
![image](https://github.com/saringrg/TMS/assets/128477532/1f82516f-a148-414f-8a78-4289e4f57532)
I have made changes in the code so, please review the work
