### ISSUE TITLE
Echit details of admin panel issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#23]
When i was checking echit details on admin panel there was found many error . Details was not written and there was randomly scattered words. 
<img width="1261" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/dd14e860-db4e-4ea8-bd35-817f447495af">

**Comment by sachinjnk99** [comment]
![image](https://github.com/saringrg/TMS/assets/128477532/6ce6e1dd-9d0e-4a4d-8f47-43d847d91c44)
please review the updated design
