### ISSUE TITLE
E-chit of traffic panel issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#24]
When i was testing E-chit on traffic panel there was found true instead of finebox so i would like  yajan to correct and post. Thank you
![image](https://github.com/saringrg/TMS/assets/128671409/5a6a6e81-328a-4fcd-91c6-c243647c142a)

**Comment by Yajan28** [comment]
<img width="331" alt="image" src="https://github.com/saringrg/TMS/assets/127926933/8f3126b1-c7c2-42f7-8fe1-f805ec9bc4b9">

**Comment by tseringklama** [comment]
Thank you.
