### ISSUE TITLE
Regex not applied on password. 

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#25]
When i was testing signup form  it accept any password instead of regex condition applied so i would like to assign yajan ko solve this bug.  Thank you
![image](https://github.com/saringrg/TMS/assets/128671409/5b0889b3-53e9-4cf9-a43c-5f4a651a2e55)

**Comment by Yajan28** [comment]
<img width="332" alt="image" src="https://github.com/saringrg/TMS/assets/127926933/14479bad-1916-482f-ae28-e593f194c8b6">

**Comment by tseringklama** [comment]
Thank you.
