### ISSUE TITLE
Echit details of admin panel issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#26]
While i was testing admin panel and clicking e-chit details, There i clicked into edit i found that there is error instead of form fo echit to tick for payment. 
![image](https://github.com/saringrg/TMS/assets/128671409/41909972-c7a8-46a4-88eb-bc371b3586d5)

**Comment by Yajan28** [comment]
<img width="331" alt="image" src="https://github.com/saringrg/TMS/assets/127926933/a7e8623f-fd3c-4a1e-944e-23b1726d390f">

**Comment by tseringklama** [comment]
Thank you.
