### ISSUE TITLE
Admin panel Dashbard issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#27]
While i was testing admin panel there first shows Dashboard and alignment of Number of echit,user and traffic was not correct so i would like to assign sachin to solve this. Thank you
<img width="1259" alt="Screen Shot 2023-05-15 at 12 34 11" src="https://github.com/saringrg/TMS/assets/128671409/4027ffc7-7111-4b6b-8719-f2b856630bdd">

**Comment by sachinjnk99** [comment]
![image](https://github.com/saringrg/TMS/assets/128477532/9e132fd8-572c-44a2-88d6-d5a85165106e)
Hello, I have changed the design of admin dashboard 
please, review the design
