### ISSUE TITLE
Traffic details issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#29]
While i was testing traffic details in admin panel it was found that button color of edit and delete was blue instead of green in edit and red in delete. I would like manshi to solve this issue.
<img width="779" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/04328c31-0e62-4297-b514-3d071ff00311">

**Comment by manshigrg** [comment]
![image](https://github.com/saringrg/TMS/assets/128445802/4a1c95ef-b687-4027-b861-380f68d043ec)
the buttons have been updated

**Comment by tseringklama** [comment]
Thank you Manshi.
