### ISSUE TITLE
Finebox Issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#3]

**Comment by tseringklama** [comment]
Manshi while i was checking E-Chit form i found that there is Up/Down arrow that number is increasing and decreasing number which will create problem in our project.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/128671409/229112870-d0898b57-5de8-4f83-9f01-1f486b1af5d3.png">

**Comment by manshigrg** [comment]
![Screenshot 2023-03-31 173527](https://user-images.githubusercontent.com/128445802/229113252-1a462161-1dc5-4c9b-baa7-391d4f683ba4.png)
the correction has been made and the code too has been updated
![Screenshot 2023-03-31 173753](https://user-images.githubusercontent.com/128445802/229113354-a506f217-1054-4629-8410-abdd023c276c.png)

**Comment by tseringklama** [comment]
Thank you Manshi. you did well.
