### ISSUE TITLE
Echit details information issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#30]
While testing echit details there was missing action features so i would like manshi to correct it Thank you.
<img width="783" alt="image" src="https://github.com/saringrg/TMS/assets/128671409/d4299db4-3c0f-4c6e-a9d7-1ddea2503dc5">

**Comment by manshigrg** [comment]
![image](https://github.com/saringrg/TMS/assets/128445802/6472f4b0-8e29-4289-86b0-1ff2d6b7d946)
the action heading has been added

**Comment by tseringklama** [comment]
Thank you Manshi.
