### ISSUE TITLE
Notice Issue.

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#4]

**Comment by sachinjnk99** [comment]
![image](https://user-images.githubusercontent.com/128477532/229266506-bfb27566-75b9-4edf-b6b7-15e1c789cd55.png)
I have made changed

**Comment by tseringklama** [comment]
Thank you Sachin, I adore your hardwork that you kept it in.

**Comment by tseringklama** [comment]
Hello Sachin, I have assigned you to solve the issue regarding Notice which have mixed language. 
<img width="685" alt="Screen Shot 2023-03-31 at 13 01 59" src="https://user-images.githubusercontent.com/128671409/229270523-d7c3ace5-166e-4755-8e79-78dd019e432d.png">

**Comment by sachinjnk99** [comment]
closed
