### ISSUE TITLE
E-Chit Pdf 

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#5]
Hi sarin, While i was checking E-Chit pdf on my Gmail there was one issue. Title of E-Chit is not in right way as it is in form and can you add some spacing in Vehicle Number,Licence Number and so on.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/128671409/229117119-f571d61b-78ad-45de-a92f-9ae52e8b2463.png">

**Comment by saringrg** [comment]
![error](https://user-images.githubusercontent.com/128318185/229118933-d6fc6d66-b57b-4eae-8f45-6c1b9794f9b7.jpg)
the error was caused by the above script

**Comment by saringrg** [comment]
![solved](https://user-images.githubusercontent.com/128318185/229119427-b11ce575-14a4-425f-a212-a945f5ca57de.jpg)
The code has been updated and correction has been made. The pdf generated now given outcome as below picture.
![Echit](https://user-images.githubusercontent.com/128318185/229120156-7885a490-62bd-482a-bf4d-22aa83b92329.jpg)

**Comment by tseringklama** [comment]
Thank you Sarin, I commend you for your hardwork.
