### ISSUE TITLE
Batch ID

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#6]
Hello Manshi, There is issue on Batch id user input. In placeholder of Batch ID box there is Licence Number instead of Batch ID. 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/128671409/229124815-c6674ef9-8068-459a-9011-d43c83664d00.png">

**Comment by manshigrg** [comment]
![batch](https://user-images.githubusercontent.com/128445802/229126105-65a99f12-7da9-4d79-b706-503bf498afc3.jpg)
![batchno](https://user-images.githubusercontent.com/128445802/229126124-c4861e4f-0345-413b-90dc-bbab2ccb5c82.jpg)
the code has been updated and the error has been corrected

**Comment by tseringklama** [comment]
Thank you Manshi. You did great job.
