### ISSUE TITLE
E-Chit Issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#8]
Hello Yajan, When i was checking E-Chit features and while clicking on Location of District there should be Traffic Station name but there is blank box instead. 
![image](https://user-images.githubusercontent.com/128671409/229271896-0916c334-8a57-4129-9436-2d94dfc64c1c.png)

**Comment by Yajan28** [comment]
<img width="1311" alt="Screenshot 2023-04-01 at 14 09 02" src="https://user-images.githubusercontent.com/127926933/229274996-bc881091-9b77-41a8-b7ae-8b327d2c7e09.png">

**Comment by Yajan28** [comment]
Hello tshering your issue is done.
