### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by tseringklama** [saringrg/TMS#9]
Hello Yajan, While i was checking Login panel at there i saw Mobile Number placeholder but we haven't done any Mobile number part in Sprint 1 so i would like to remove that part and let Email only in that box.
![image](https://user-images.githubusercontent.com/128671409/229276222-e7a6fd7a-44b5-4482-b5fe-efbb3430848f.png)

**Comment by Yajan28** [comment]
<img width="1435" alt="Screenshot 2023-04-01 at 14 39 18" src="https://user-images.githubusercontent.com/127926933/229276365-45c1041b-ab36-4487-89c2-e12d1af8659c.png">

**Comment by Yajan28** [comment]
ok issue is done
